
export interface IIAS {    
    ApprovalNoteNo?:any;
    SAPNo?:any;
    MovementReason?:any;
    Status?:any;
    Stage?:any;
    NAID?:any;
    NATitle?:any;
    NAEmail?:any;
    DAID?:any;
    DATitle?:any;
    DAEmail?:any;
    Details:any;
    Summary:any;
    WF:any;
    HeaderName:any;
    MovementType:any;
    Department:any;
    CostCenter:any;
    UniquePartImpact:any;
    GrossValue:any;
    NetValue:any;
    LastAction:any;
    CostCenterDescription:any; 
    AttachmentFiles:any;
    ID:number;
    Title:string;
    Author:any;
    Created:any;
    NextApproverEmpID:any;
    InitiatorEmpId:any;
    DelegateApproverEmpID:any;
    InventoryAttachment:any;
}